### ISSUE TITLE
main_1          | 35:21-40 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by patrykkopycinski** [OpusCapita/cache#1]
main_1          | WARNING in /var/tmp/base/~/ocbesbn-cache/index.js

**Comment by kwierchris** [comment]
This is a warning raised by webpack and happens due to it's weird way of parsing JS files to compile them. There are two ways of getting rid of this warning.

1. Always have hardcoded require paths which is not suitable for a plug-in system like this.
2. Not using webpack.
